name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
      - name: Install packages
        run: yarn install --pure-lockfile
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:setup
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake test:system
